server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  output:
    ansi:
      enabled: always

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**

          filters:
            - StripPrefix=1

