server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Livraria
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: auth-service
  output:
    ansi:
      enabled: always
  mail:
    host: sandbox.smtp.mailtrap.io   
    port: 587
    username: d023fdabd70383
    password: b1aae1d24ae790
    properties:
      mail:
        smlp:
          auth: true
          starttls:
            enable: true
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
