server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Livraria
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
  output:
    ansi:
      enabled: always
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 76c6a11cd97a5b
    password: 3d40d82d5af353
    properties:
      mail:
        smlp:
          auth: true
          starttls:
            enable: true
  flyway:
    baseline-on-migrate: true
