server:
  port: 0
spring:
  application:
    name: book-service
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/Livraria
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
